Repository 42Box/macOS, pull requests merged in 2023-08, with the labels that each got.

#25 feat(tuist): tuist를 추가하였습니다.
  Project.swift
Labels: enhancement

#28 feat(system): Storage 기능을 추가합니다. ✨
  Box42.xcodeproj/project.pbxproj
  Box42.xcodeproj/project.xcworkspace/xcuserdata/chanheki.xcuserdatad/UserInterfaceState.xcuserstate
  Box42/Extensions/Double.swift
  Box42/Extensions/String.swift
  Box42/Main/BoxViewController.swift
  Box42/Menubar/MenubarViewModel.swift
  Box42/Resources/AppDelegate.swift
  Box42/System/CPU.swift
  Box42/System/EventMonitor.swift
  Box42/System/Storage.swift
  Box42/System/StorageConfig.swift
Labels: enhancement

#32 feat:SPM으로 SnapKit을 설치했습니다.
  Box42.xcodeproj/project.pbxproj
  Box42.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Box42.xcodeproj/project.xcworkspace/xcuserdata/daskim.xcuserdatad/UserInterfaceState.xcuserstate
  Box42/Box/BoxButtonViewGroup.swift
  Box42/Main/BoxViewController.swift
  Box42/Menubar/MenubarViewController.swift
  Box42/Resources/Main.storyboard
  Box42/System/EventMonitor.swift
  Box42/Window/BoxWindowController.swift
Labels: enhancement, good first issue

#34 build(tuist): Snapkit 도입을 위해 외부 종속성을 추가합니다
  Box42/Resources/sh/brewInGoinfre.sh
  Box42/Resources/sh/cleanCache.sh
  Box42/Resources/sh/exportMacOSInfo.sh
  Box42/Resources/sh/importMacOSInfo.sh
  Box42/Resources/sh/keyMapping.sh
  Box42/Resources/sh/nodeInstall.sh
  Project.swift
  Tuist/Dependencies.swift
Labels: documentation, enhancement, DevOps

#39 test: swift.yml 🛠
  .github/workflows/swift.yml
  Package.swift
Labels: documentation, DevOps

#71 refactor: refactoring to NSTable with NSbuttons.
  Box42/Box/BoxBaseContainerViewController.swift
  Box42/Box/View/BoxButtonViewGroup.swift
  Box42/Box/View/BoxContentsViewGroup.swift
  Box42/Window/BoxWindowController.swift
Labels: ⚒ Refactor

#57 fix: toolbar 관련 사항 변경
  Box42/Box/BoxBaseContainerViewController.swift
  Box42/Box/View/BoxButtonViewGroup.swift
  Box42/FunctionButton/View/BoxFunctionViewGroup.swift
  Box42/Main/BoxViewController.swift
  Box42/Toolbar/ToolbarViewController.swift
  Box42/Toolbar/View/BoxToolbarViewGroup.swift
  Box42/WebView/URL/URLModel.swift
  Box42/Window/BoxWindowController.swift
  Box42/Window/View/WindowCloseButton.swift
  Box42/Window/View/WindowMaximizeButton.swift
  Box42/Window/View/WindowMinimizeButton.swift
  Box42/Window/View/WindowViewGroup.swift
  Box42/Window/WindowButtonViewController.swift
Labels: ✨ Enhancement, 🌐 DevOps

#82 feat: quick slot
  Box42.xcodeproj/project.pbxproj
  Box42/BoxWindowController.swift
  Box42/FunctionButton/Model/FunctionButtonUI.swift
  Box42/FunctionButton/View/BoxFunctionViewGroup.swift
  Box42/Main/BoxBaseContainerViewController.swift
  Box42/Menubar/MenubarViewController.swift
  Box42/Menubar/MenubarViewModel.swift
  Box42/Preferences/PreferencesViewController.swift
  Box42/QuickSlot/Controller/QuickSlotScriptsLogicController.swift
  Box42/QuickSlot/Controller/QuickSlotViewController.swift
  Box42/QuickSlot/Model/QuickSlotButtonModel.swift
  Box42/QuickSlot/Model/QuickSlotUI.swift
  Box42/QuickSlot/View/ButtonCollectionView/QuickSlotButtonCollectionViewController.swift
  Box42/QuickSlot/View/ButtonCollectionView/QuickSlotButtonCollectionViewController.xib
  Box42/QuickSlot/View/ButtonCollectionView/Vertical Item/QuickSlotButtonViewItem.swift
  Box42/QuickSlot/View/ButtonCollectionView/Vertical Item/QuickSlotButtonViewItem.xib
  Box42/QuickSlot/View/Divider.swift
  Box42/QuickSlot/View/QuickSlotGroupView.swift
  Box42/QuickSlot/View/QuickSlotHeaderView.swift
  Box42/QuickSlot/ViewModel/QuickSlotViewModel.swift
  Box42/Resources/AppDelegate.swift
  Box42/Resources/Assets.xcassets/42pack_icon/sitting_fox/Contents.json
  Box42/Resources/Assets.xcassets/42pack_icon/sitting_fox/sitting_fox0.imageset/Contents.json
  Box42/Resources/Assets.xcassets/42pack_icon/sitting_fox/sitting_fox0.imageset/sitting_fox0.png
  Box42/Resources/Assets.xcassets/42pack_icon/sitting_fox/sitting_fox1.imageset/Contents.json
  Box42/Resources/Assets.xcassets/42pack_icon/sitting_fox/sitting_fox1.imageset/sitting_fox1.png
  Box42/Resources/Assets.xcassets/42pack_icon/sitting_fox/sitting_fox2.imageset/Contents.json
  Box42/Resources/Assets.xcassets/42pack_icon/sitting_fox/sitting_fox2.imageset/sitting_fox2.png
  Box42/Resources/Assets.xcassets/42pack_icon/sitting_fox/sitting_fox3.imageset/Contents.json
  Box42/Resources/Assets.xcassets/42pack_icon/sitting_fox/sitting_fox3.imageset/sitting_fox3.png
  Box42/Resources/Assets.xcassets/uibuttons/Bookmark.imageset/Bookmark icon.png
  Box42/Resources/Assets.xcassets/uibuttons/Bookmark.imageset/Contents.json
  Box42/Resources/Assets.xcassets/uibuttons/Pin icon.png
  Box42/Resources/Assets.xcassets/uibuttons/Star.imageset/Contents.json
  Box42/Resources/Assets.xcassets/uibuttons/Star.imageset/Star 3.png
  Box42/Resources/Assets.xcassets/uibuttons/pin-box-ver.imageset/Contents.json
  Box42/Resources/Assets.xcassets/uibuttons/pin-box-ver.imageset/Pin icon.png
  Box42/Resources/Assets.xcassets/uibuttons/pin-box.imageset/Contents.json
  Box42/Resources/Assets.xcassets/uibuttons/pin-box.imageset/Pin icon_45.png
  Box42/Shared/Constants.swift
  Box42/Shared/NotifConst.swift
  Box42/WebView/URL/URLModel.swift
  Box42/WindowButton/Model/WindowButtonUI.swift
Labels: ✨ Enhancement

#89 feat: webview 의 icon 변경 기능을 구현합니다
  Box42.xcodeproj/project.pbxproj
  Box42/Icon/IconChanged+WebView.swift
  Box42/Menubar/MenubarModel.swift
  Box42/Menubar/MenubarViewModel.swift
  Box42/Preferences/Icon.swift
  Box42/Resources/AppDelegate.swift
  Box42/Shared/Constants.swift
  Box42/System/CPU.swift
  Box42/Toolbar/Controller/ToolbarViewController.swift
  Box42/Toolbar/View/DisplayURL/DisplayURLInToolbar.swift
  Box42/Toolbar/View/DisplayURL/DisplayURLTextfield.swift
  Box42/WebView/Model/URLModel.swift
  Box42/WebView/Model/UserProfile.swift
  Box42/WebView/URL/URLModel.swift
  Box42/WebView/WebViewManager.swift
Labels: ✨ Enhancement

#93 feat: front <-> app 통신
  Box42.xcodeproj/project.pbxproj
  Box42/Icon/IconChanged+WebView.swift
  Box42/Menubar/MenubarViewController.swift
  Box42/Preferences/PreferencesViewController.swift
  Box42/Toolbar/View/DisplayURL/DisplayURLInToolbar.swift
  Box42/WebView/WebView.swift
  Box42/WebView/WebViewController.swift
  Box42/WebView/WebViewManager.swift
Labels: ✨ Enhancement

#101 feat: script를 quickslot에서 등록 후 실행까지 하게 합니다.
  Box42.xcodeproj/project.pbxproj
  Box42/Extensions/Associated+NSButton.swift
  Box42/FunctionButton/BoxFunctionViewController.swift
  Box42/QuickSlot/Controller/QuickSlotScriptsLogicController.swift
  Box42/QuickSlot/Model/QuickSlotButtonModel.swift
  Box42/QuickSlot/View/ButtonCollectionView/QuickSlotButtonCollectionViewController.swift
  Box42/Scripts/Model/Scripts.swift
  Box42/Scripts/View/Table/ScriptCellManager.swift
  Box42/Scripts/View/Table/ScriptsTableView.swift
  Box42/Scripts/ViewModel/ScriptsViewModel.swift
Labels: ✨ Enhancement

#107 fix: swift build error fix
  Box42.xcodeproj/project.pbxproj
  Box42/Preferences/Accessibility.swift
  Box42/Preferences/Controller/PreferencesViewController.swift
  Box42/Preferences/Hotkey.swift
  Box42/Preferences/PreferencesView.swift
  Box42/Preferences/PreferencesViewController.swift
  Box42/Preferences/View/PreferencesCell.swift
  Package.resolved
Labels: 🐞 Bug

#109 feat: script를 API 규격에 맞춥니다.
  Box42.xcodeproj/project.pbxproj
  Box42/Resources/AppDelegate.swift
  Box42/Scripts/Controller/ExecuteScripts.swift
  Box42/Scripts/Controller/ScriptsViewController.swift
  Box42/Scripts/Model/Scripts.swift
  Box42/Scripts/View/Button/ScriptQuickSlotButton.swift
  Box42/Scripts/View/Table/ScriptCell.swift
  Box42/Scripts/ViewModel/ScriptsViewModel.swift
  Box42/Shared/API/API.swift
  Box42/Shared/API/GetUserMeScripts.swift
  Box42/Shared/API/GetUserProfile.swift
  Box42/WebView/Model/WebViewUI.swift
  Box42/WebView/WebView.swift
Labels: ✨ Enhancement

#111 feat: 유저에게 권한을 받습니다.
  Box42/Preferences/Controller/PreferencesViewController.swift
  Box42/Preferences/View/PreferencesTableView.swift
  Box42/Preferences/View/RequestAccessView.swift
  Box42/QuickSlot/Controller/QuickSlotScriptsLogicController.swift
  Box42/QuickSlot/ViewModel/QuickSlotViewModel.swift
  Box42/Resources/Info.plist
  Box42/Scripts/Controller/ScriptsFileManager.swift
  Box42/Shared/SecurityScopedResourceAccess.swift
Labels: ✨ Enhancement

#113 feat: stroage 관련 UI view를 추가합니다.
  Box42.xcodeproj/project.pbxproj
  Box42/Main/keyDown+BoxBaseContainerViewController.swift
  Box42/Preferences/View/Funtion/RequestAccessView.swift
  Box42/Preferences/View/Funtion/StorageView.swift
  Box42/Preferences/View/Table/PreferencesCell.swift
  Box42/Preferences/View/Table/PreferencesTableView.swift
Labels: ✨ Enhancement
