Repository 42Box/macOS, pull requests merged in 2023-09, with the labels that each got.

#120 feat: preference prototype
  Box42.xcodeproj/project.pbxproj
  Box42/Preferences/View/Funtion/BatteryView.swift
  Box42/Preferences/View/Funtion/CPUView.swift
  Box42/Preferences/View/Funtion/IconSettingView.swift
  Box42/Preferences/View/Funtion/MemoryView.swift
  Box42/Preferences/View/Funtion/NetworkView.swift
  Box42/Preferences/View/Funtion/NotificationSettingView.swift
  Box42/Preferences/View/Funtion/RequestAccessView.swift
  Box42/Preferences/View/Funtion/ShortcutSettingView.swift
  Box42/Preferences/View/Funtion/StorageView.swift
  Box42/Preferences/View/Table/PreferencesCell.swift
  Box42/Preferences/View/Table/PreferencesTableView.swift
  Box42/Resources/Box42.entitlements
  Box42/Resources/Info.plist
  Box42/Shared/API/DeleteUserMeScript.swift
  Box42/Shared/SecurityScopedResourceAccess.swift
Labels: ✨ Enhancement

#121 refactor: script crud
  Box42/Menubar/MenubarViewController.swift
  Box42/QuickSlot/Model/QuickSlotButtonModel.swift
  Box42/QuickSlot/View/ButtonCollectionView/QuickSlotButtonCollectionViewController.swift
  Box42/QuickSlot/ViewModel/QuickSlotViewModel.swift
  Box42/Resources/AppDelegate.swift
  Box42/Scripts/Controller/ScriptsViewController.swift
  Box42/Scripts/Model/Scripts.swift
  Box42/Scripts/View/Table/ScriptsTableView.swift
  Box42/Scripts/ViewModel/ScriptsViewModel.swift
  Box42/Shared/API/API.swift
  Box42/Shared/API/DeleteUserMeScript.swift
  Box42/Shared/API/GetUserMeScripts.swift
  Box42/Shared/API/GetUserProfile.swift
  Box42/Shared/User/UserProfile.swift
  Box42/WebView/Model/WebViewUI.swift
  Box42/WebView/WebView.swift
  Box42/WebView/WebViewManager.swift
Labels: ✨ Enhancement

#116 fix:be able to go the new tab in web view and open NSOpenPanel from the webview.
  Box42.xcodeproj/project.pbxproj
  Box42.xcodeproj/project.xcworkspace/xcuserdata/daskim.xcuserdatad/UserInterfaceState.xcuserstate
  Box42/QuickSlot/View/QuickSlotGroupView.swift
  Box42/Resources/Info.plist
  Box42/Toolbar/Controller/ToolbarViewController.swift
  Box42/Toolbar/View/SideBarLeading.swift
  Box42/View/BoxContentsViewGroup.swift
Labels: ✨ Enhancement

#129 refactor: refactoring the main view.
  Box42.xcodeproj/project.pbxproj
  Box42.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Box42/Main/BoxBaseContainerViewController.swift
  Box42/Main/BoxWindowController.swift
  Box42/Main/UI/HoverButton.swift
  Box42/Main/UI/MovableContainerView.swift
  Box42/Main/View/BookmarkEditorView.swift
  Box42/Main/View/BoxBaseSplitView.swift
  Box42/Main/View/BoxContentsViewGroup.swift
  Box42/QuickSlot/View/QuickSlotGroupView.swift
  Box42/Resources/Assets.xcassets/Icons/bookmark-default.imageset/42Box icon 1.png
  Box42/Resources/Assets.xcassets/Icons/bookmark-default.imageset/42Box icon 2.png
  Box42/Resources/Assets.xcassets/Icons/bookmark-default.imageset/42Box icon.png
  Box42/Resources/Assets.xcassets/Icons/bookmark-default.imageset/Contents.json
  Box42/View/BoxContentsViewGroup.swift
Labels: ✨ Enhancement

#132 feat: design quickslot and editor view
  Box42/FunctionButton/View/PinButtonView.swift
  Box42/Main/BoxBaseContainerViewController.swift
  Box42/Preferences/View/Funtion/CPUView.swift
  Box42/Preferences/View/Funtion/IconSettingView.swift
  Box42/Preferences/View/Funtion/NotificationSettingView.swift
  Box42/Preferences/View/Funtion/RequestAccessView.swift
  Box42/Preferences/View/Funtion/ShortcutSettingView.swift
  Box42/Preferences/View/Funtion/StorageView.swift
  Box42/Preferences/View/Table/PreferencesTableView.swift
  Box42/QuickSlot/Controller/QuickSlotManagerViewController.swift
  Box42/QuickSlot/View/ButtonCollectionView/QuickSlotButtonCollectionViewController.swift
  Box42/QuickSlot/View/ButtonCollectionView/Vertical Item/QuickSlotItemButton.swift
  Box42/QuickSlot/View/QuickSlotGroupView.swift
  Box42/QuickSlot/View/QuickSlotHeaderView.swift
  Box42/QuickSlot/View/Table/QuickSlotCell.swift
  Box42/QuickSlot/View/Table/QuickSlotCellDeleteButton.swift
  Box42/QuickSlot/View/Table/QuickSlotTableView.swift
  Box42/Resources/Assets.xcassets/uibuttons/Bookmark.imageset/Bookmark icon 1.png
  Box42/Resources/Assets.xcassets/uibuttons/Bookmark.imageset/Bookmark icon 2.png
  Box42/Resources/Assets.xcassets/uibuttons/Bookmark.imageset/Bookmark icon 3.png
  Box42/Resources/Assets.xcassets/uibuttons/Bookmark.imageset/Contents.json
  Box42/Scripts/View/Button/ScriptDeleteButton.swift
  Box42/Scripts/View/Button/ScriptExcuteButton.swift
  Box42/Scripts/View/Button/ScriptQuickSlotButton.swift
  Box42/Scripts/View/Table/ScriptCell.swift
  Box42/Scripts/View/Table/ScriptsTableView.swift
  Box42/Toolbar/Controller/ToolbarViewController.swift
  Box42/Toolbar/View/BoxToolbarViewGroup.swift
  Box42/Toolbar/View/SideBarLeading.swift
Labels: 💄 UI/UX

#145 refactor: 전체적인 서비스 변경
  Box42.xcodeproj/project.pbxproj
  Box42/Bookmark/Model/BookmarkModel.swift
  Box42/Bookmark/View/Button/BookmarkCreateButton.swift
  Box42/Bookmark/View/Editor/BookmarkCell.swift
  Box42/Bookmark/View/Editor/BookmarkCellManager.swift
  Box42/Bookmark/View/Editor/BookmarkEditorTableView.swift
  Box42/Bookmark/ViewModel/BookmarkViewModel.swift
  Box42/Main/BoxBaseContainerViewController.swift
  Box42/Main/BoxWindowController.swift
  Box42/Preferences/View/Funtion/StorageView.swift
  Box42/QuickSlot/Controller/QuickSlotScriptsLogicController.swift
  Box42/QuickSlot/Controller/QuickSlotViewController.swift
  Box42/QuickSlot/View/ButtonCollectionView/Vertical Item/QuickSlotItemButton.swift
  Box42/QuickSlot/View/QuickSlotGroupView.swift
  Box42/QuickSlot/View/Table/QuickSlotTableCell.swift
  Box42/QuickSlot/View/Table/QuickSlotTableView.swift
  Box42/QuickSlot/ViewModel/QuickSlotViewModel.swift
  Box42/Resources/AppDelegate.swift
  Box42/Resources/Assets.xcassets/AppIcon.appiconset/16.png
  Box42/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Box42/Resources/Assets.xcassets/AppIcons/appstore.imageset/1024-1.png
  Box42/Resources/Assets.xcassets/AppIcons/appstore.imageset/1024-2.png
  Box42/Resources/Assets.xcassets/AppIcons/appstore.imageset/1024.png
  Box42/Resources/Assets.xcassets/AppIcons/appstore.imageset/Contents.json
  Box42/Resources/Assets.xcassets/AppIcons/appstore.imageset/appstore.png
  Box42/Resources/Assets.xcassets/AppIcons/playstore.imageset/1024-1.png
  Box42/Resources/Assets.xcassets/AppIcons/playstore.imageset/1024-2.png
  Box42/Resources/Assets.xcassets/AppIcons/playstore.imageset/1024.png
  Box42/Resources/Assets.xcassets/AppIcons/playstore.imageset/Contents.json
  Box42/Resources/Assets.xcassets/AppIcons/playstore.imageset/playstore.png
  Box42/Resources/Assets.xcassets/logos/42box_logo 1.imageset/42box_logo.svg
  Box42/Resources/Assets.xcassets/logos/42box_logo 1.imageset/Contents.json
  Box42/Resources/Assets.xcassets/logos/42box_logo 1.imageset/Icon 1024 - no BG dot-1024.png
  Box42/Resources/Assets.xcassets/logos/42box_logo 1.imageset/Icon 1024 - no BG dot-1025.png
  Box42/Resources/Assets.xcassets/logos/42box_logo 1.imageset/Icon 1024 - no BG dot-1026.png
  Box42/Resources/Assets.xcassets/logos/42box_logo.imageset/42box_logo.png
  Box42/Resources/Assets.xcassets/logos/42box_logo.imageset/Contents.json
  Box42/Resources/Assets.xcassets/logos/42box_logo.imageset/Icon 1024 - no BG dot-1024.png
  Box42/Resources/Assets.xcassets/logos/42box_logo.imageset/Icon 1024 - no BG dot-1025.png
  Box42/Resources/Assets.xcassets/logos/42box_logo.imageset/Icon 1024 - no BG dot-1026.png
  Box42/Resources/Info.plist
  Box42/Resources/sh/CleanCache_cluster.sh
  Box42/Scripts/Controller/ExecuteScripts.swift
  Box42/Scripts/Model/Scripts.swift
  Box42/Scripts/ViewModel/ScriptsViewModel.swift
  Box42/Shared/API/GetUserMeScripts.swift
  Box42/Shared/SecurityScopedResourceAccess.swift
  Box42/Shared/User/UserProfile.swift
  Box42/System/Storage.swift
  Box42/Toolbar/Controller/ToolbarViewController.swift
  Box42/Toolbar/View/DisplayURL/DisplayURLInToolbar.swift
  Box42/Toolbar/View/DisplayURL/DisplayURLTextfield.swift
  Box42/WebView/WebViewManager.swift
Labels: ⚒ Refactor
